"""Coverage, uncertainty and gap reports: what the evidence base actually supports.

Three questions, answered from the four registries rather than from memory:

```text
coverage      for every cluster and every rule: which sources, which claims, which parameters,
              and which support class — and where the chain is broken
uncertainty   for every parameter: its grade, its support class, whether a range exists, what the
              range rests on, and whether it is a sensitivity candidate
gaps          what is missing: clusters with no sources or no patterns, parameters whose support is
              nothing but a placeholder, unverified records, and the human-only acquisition queue
```

The reports are strings on purpose. They are written to `docs/evidence/` by the phase's own entry
point, and every number in them is counted from the loaded registries, so a report cannot drift
from the data it describes. Nothing here scores the model or fits anything: a coverage number is a
statement about the evidence base, never about the model's correctness.
"""

from __future__ import annotations

from collections import Counter
from typing import Final

from late_ming_lab.evidence.cards import ParameterCards, SupportClass
from late_ming_lab.evidence.grades import EvidenceGrade
from late_ming_lab.evidence.ledger import (
    CalibrationRole,
    EvidenceLedger,
    PatternRegistry,
    RuleClaimSet,
)
from late_ming_lab.evidence.registry import (
    EVIDENCE_CLUSTERS,
    SourceRegistry,
    Verification,
)

GRADES_IN_ORDER: Final[tuple[EvidenceGrade, ...]] = (
    EvidenceGrade.A,
    EvidenceGrade.B,
    EvidenceGrade.C,
    EvidenceGrade.D,
    EvidenceGrade.S,
)

SUPPORT_IN_ORDER: Final[tuple[SupportClass, ...]] = (
    SupportClass.EVIDENCE_BACKED,
    SupportClass.THEORETICALLY_ASSUMED,
    SupportClass.EXPLORATORY,
)


def _grade_counts(grades: list[EvidenceGrade]) -> str:
    counts = Counter(grade.value for grade in grades)
    return ", ".join(f"{grade.value}:{counts.get(grade.value, 0)}" for grade in GRADES_IN_ORDER)


def coverage_report(
    *,
    registry: SourceRegistry,
    ledger: EvidenceLedger,
    cards: ParameterCards,
    patterns: PatternRegistry,
    rules: RuleClaimSet,
) -> str:
    """Per-cluster and per-rule coverage, with the breaks named rather than summarised away."""
    rendered_support = ", ".join(
        f"{name}:{count}" for name, count in sorted(support_summary(rules).items())
    )
    rendered_roles = ", ".join(
        f"{role.value}:{len(patterns.by_role(role))}" for role in CalibrationRole
    )
    lines: list[str] = [
        "# Evidence coverage",
        "",
        "Generated by `late_ming_lab.evidence.coverage` from the source registry, the evidence",
        "ledger, the parameter cards, the rule claims and the pattern registry. Every count in it",
        "is counted, not estimated.",
        "",
        f"- sources: {len(registry)} ({_grade_counts([r.grade for r in registry])})",
        f"- ledger entries: {len(ledger)}",
        f"- parameter cards: {len(cards)} "
        f"({_grade_counts([card.evidence_grade for card in cards])})",
        f"- declared rules: {len(rules)} ({rendered_support})",
        f"- historical patterns: {len(patterns)} ({rendered_roles})",
        "",
        "## By cluster",
        "",
        "| cluster | sources | layers | claims (strength) | parameters supported | patterns |",
        "| --- | --- | --- | --- | --- | --- |",
    ]
    for cluster in EVIDENCE_CLUSTERS:
        sources = registry.by_cluster(cluster)
        entries = ledger.by_cluster(cluster)
        cluster_patterns = patterns.by_cluster(cluster)
        layers = Counter(source.layer.value for source in sources)
        strengths = Counter(entry.strength.value for entry in entries)
        supported: set[str] = set()
        for entry in entries:
            supported.update(entry.supports_parameters)
        rendered_layers = (
            ", ".join(f"{name}:{count}" for name, count in sorted(layers.items())) or "-"
        )
        rendered_strengths = (
            ", ".join(f"{name}:{count}" for name, count in sorted(strengths.items())) or "-"
        )
        lines.append(
            f"| {cluster} | {len(sources)} | {rendered_layers} | {rendered_strengths} | "
            f"{len(supported)} | {len(cluster_patterns)} |"
        )

    lines += [
        "",
        "## Parameters by support class and grade",
        "",
        "| parameter set | cards | evidence-backed | theoretically-assumed | exploratory | "
        "grades |",
        "| --- | --- | --- | --- | --- | --- |",
    ]
    sets = sorted({card.parameter_set for card in cards})
    for parameter_set in sets:
        group = cards.for_set(parameter_set)
        classes = Counter(card.support_class.value for card in group)
        lines.append(
            f"| {parameter_set} | {len(group)} | "
            f"{classes.get(SupportClass.EVIDENCE_BACKED.value, 0)} | "
            f"{classes.get(SupportClass.THEORETICALLY_ASSUMED.value, 0)} | "
            f"{classes.get(SupportClass.EXPLORATORY.value, 0)} | "
            f"{_grade_counts([card.evidence_grade for card in group])} |"
        )

    lines += [
        "",
        "## Rules",
        "",
        "| rule | support class | parameters | ledger entries |",
        "| --- | --- | --- | --- |",
    ]
    for rule in rules:
        lines.append(
            f"| {rule.name} | {rule.support_class.value} | {len(rule.parameters)} | "
            f"{len(rule.ledger_entries)} |"
        )

    orphan_entries = sorted(
        {
            entry_id
            for rule in rules
            for entry_id in rule.ledger_entries
            if not any(entry.id == entry_id for entry in ledger)
        }
    )
    dangling_parameters = sorted(
        {
            parameter
            for entry in ledger
            for parameter in entry.supports_parameters
            if not _parameter_is_declared(cards, parameter)
        }
    )
    lines += [
        "",
        "## Breaks in the chain",
        "",
        f"- ledger entries cited by a rule but absent from the ledger: "
        f"{', '.join(orphan_entries) if orphan_entries else 'none'}",
        f"- parameters cited by a claim but absent from the cards: "
        f"{', '.join(dangling_parameters) if dangling_parameters else 'none'}",
        f"- clusters with no sources: {', '.join(registry.clusters_without_sources()) or 'none'}",
        f"- clusters with no ledger entries: "
        f"{', '.join(ledger.clusters_without_entries()) or 'none'}",
        f"- clusters with no recorded pattern: "
        f"{', '.join(patterns.clusters_without_patterns()) or 'none'}",
        "",
    ]
    return "\n".join(lines)


def _parameter_is_declared(cards: ParameterCards, qualified: str) -> bool:
    """True when ``Set.field`` names a card in the registry."""
    if "." not in qualified:
        return False
    parameter_set, parameter = qualified.split(".", 1)
    return cards.get(parameter_set, parameter) is not None


def uncertainty_report(cards: ParameterCards) -> str:
    """Every parameter's grade, range and reasoning, with the unsourced ones listed separately."""
    lines: list[str] = [
        "# Parameter uncertainty",
        "",
        "One row per parameter card. `central` is the value the model currently uses; `range` is",
        "what the evidence would allow instead, and is empty where nobody has established one.",
        "Grade `S` means the value is a model assumption and nothing more. Grade `D` means the",
        "evidence is weak but exists. Both are sensitivity candidates by the project's rule.",
        "",
        f"- cards: {len(cards)}",
        f"- with a stated range: {sum(1 for c in cards if c.range and c.range.has_bounds)}",
        f"- grade S: {sum(1 for c in cards if c.evidence_grade is EvidenceGrade.S)}",
        f"- grade D: {sum(1 for c in cards if c.evidence_grade is EvidenceGrade.D)}",
        f"- sensitivity candidates: {len(cards.sensitivity_candidates)}",
        "",
        "## Cards",
        "",
        "| parameter | set | grade | class | central | unit | range | range basis | sensitivity |",
        "| --- | --- | --- | --- | --- | --- | --- | --- | --- |",
    ]
    for card in cards:
        if card.range and card.range.has_bounds:
            spread = f"{card.range.low}-{card.range.high}"
            basis = card.range.basis.replace("|", "/")
        else:
            spread = "—"
            basis = "—"
        central = card.value_in_use.replace("|", "/") or "-"
        lines.append(
            f"| {card.id} | {card.parameter_set} | {card.evidence_grade.value} | "
            f"{card.support_class.value} | {central} | {card.unit} | {spread} | {basis} | "
            f"{card.sensitivity_priority} |"
        )

    conflicts = [card for card in cards if card.range is not None and card.range.conflicts]
    lines += ["", "## Recorded conflicts", ""]
    if conflicts:
        for card in conflicts:
            recorded = card.range
            assert recorded is not None
            lines.append(f"- **{card.parameter_set}.{card.id}**: {recorded.conflicts}")
    else:
        lines.append("- none: no card currently records two sources that disagree.")
    lines.append("")
    return "\n".join(lines)


def gap_report(
    *,
    registry: SourceRegistry,
    ledger: EvidenceLedger,
    cards: ParameterCards,
    patterns: PatternRegistry,
    rules: RuleClaimSet,
) -> str:
    """What is missing, including the acquisition queue that only a human may work."""
    unverified = [source for source in registry if source.verification is Verification.UNVERIFIED]
    restricted = [source for source in registry if source.acquisition_is_human_only]
    unexplained_rules = [
        rule
        for rule in rules
        if not rule.ledger_entries and rule.support_class is not SupportClass.EXPLORATORY
    ]
    bare_parameters = [
        card for card in cards if card.evidence_grade is EvidenceGrade.S and not card.sources
    ]
    unreferenced_parameters = [card for card in bare_parameters if not card.ledger_entries]
    lines: list[str] = [
        "# Evidence gaps",
        "",
        "Generated from the registries. A gap is a place where the chain from claim to code is",
        "missing, not a place where the model is wrong.",
        "",
        "## Clusters",
        "",
    ]
    for cluster in EVIDENCE_CLUSTERS:
        missing: list[str] = []
        if not registry.by_cluster(cluster):
            missing.append("no sources")
        if not ledger.by_cluster(cluster):
            missing.append("no claims")
        if not patterns.by_cluster(cluster):
            missing.append("no pattern")
        lines.append(f"- **{cluster}**: {'; '.join(missing) if missing else 'covered'}")

    lines += [
        "",
        "## Rules with no evidence behind them",
        "",
        f"{len(unexplained_rules)} declared rule(s) cite no ledger entry and are not declared",
        "exploratory. Each is either a rule waiting for evidence or a rule mislabelled as",
        "theoretically assumed:",
        "",
    ]
    for rule in unexplained_rules:
        lines.append(f"- **{rule.name}** (`{rule.module}`, class `{rule.support_class.value}`)")
    if not unexplained_rules:
        lines.append("- none")

    framed = [card for card in bare_parameters if card.ledger_entries]
    lines += [
        "",
        "## Parameters whose value is still ours",
        "",
        f"{len(bare_parameters)} of {len(cards)} parameters are grade S with no source fixing the",
        f"value. Of those, {len(framed)} are framed by at least one ledger claim (the record",
        f"establishes the mechanism and its order of magnitude) and {len(unreferenced_parameters)}",
        "have no claim attached at all — those are the thinnest places in the model:",
        "",
    ]
    by_set = Counter(card.parameter_set for card in bare_parameters)
    unreferenced_by_set = Counter(card.parameter_set for card in unreferenced_parameters)
    for name, count in sorted(by_set.items()):
        total = len(cards.for_set(name))
        lines.append(
            f"- {name}: {count} of {total} grade S "
            f"({unreferenced_by_set.get(name, 0)} with no claim attached)"
        )

    lines += [
        "",
        "## Unverified bibliographic records",
        "",
        f"{len(unverified)} of {len(registry)} source records were recorded but not confirmed",
        "against a locator in this phase. A claim resting on one may not exceed grade C:",
        "",
    ]
    for source in unverified:
        lines.append(f"- `{source.id}` — {source.title} ({source.layer.value})")
    if not unverified:
        lines.append("- none")

    lines += [
        "",
        "## Acquisition queue (human only)",
        "",
        "These sources are behind institutional or manual access. **No agent may acquire them**;",
        "the registry records the condition and the locator, and a human decides what to consult:",
        "",
    ]
    for source in restricted:
        note = source.rights_note or "access condition not described"
        lines.append(f"- `{source.id}` — {source.access.value}: {note}")
    if not restricted:
        lines.append("- none")

    lines += [
        "",
        "## Structural gaps this phase did not close",
        "",
        "- No source in the registry measures a 1625-1644 Shaanxi-Henan quantity directly at the",
        "  resolution the model uses (county-month). Where a claim carries a magnitude, it is a",
        "  regional or annual figure being used at a finer resolution, and the card says so.",
        "- The registry holds no archival material: county-level quota books, relief registers and",
        "  garrison payrolls are named as gaps rather than approximated.",
        "- Nothing here calibrates anything. Every pattern carries a calibration role, and the",
        "  hold-out patterns are marked so a later phase cannot silently fit them.",
        "",
    ]
    return "\n".join(lines)


def grade_summary(cards: ParameterCards) -> dict[str, int]:
    """Grade counts over the cards, for the phase report and for tests."""
    counts = Counter(card.evidence_grade.value for card in cards)
    return {grade.value: counts.get(grade.value, 0) for grade in GRADES_IN_ORDER}


def support_summary(rules: RuleClaimSet) -> dict[str, int]:
    """Rule counts by support class, for the phase report and for tests."""
    counts = Counter(rule.support_class.value for rule in rules)
    return {support.value: counts.get(support.value, 0) for support in SUPPORT_IN_ORDER}
