"""Coverage, uncertainty and gap reports: what the evidence base actually supports.

Three questions, answered from the four registries rather than from memory:

```text
coverage      for every cluster and every rule: which sources, which claims, which parameters,
              and which support class — and where the chain is broken
uncertainty   for every parameter: its grade, its support class, whether a range exists, what the
              range rests on, and whether it is a sensitivity candidate
gaps          what is missing: clusters with no sources or no patterns, parameters whose support is
              nothing but a placeholder, unverified records, and the human-only acquisition queue
```

The reports are strings on purpose. They are written to `docs/evidence/` by the phase's own entry
point, and every number in them is counted from the loaded registries, so a report cannot drift
from the data it describes. Nothing here scores the model or fits anything: a coverage number is a
statement about the evidence base, never about the model's correctness.
"""

from __future__ import annotations

from collections import Counter
from typing import Final

from late_ming_lab.evidence.cards import ParameterCards, SupportClass
from late_ming_lab.evidence.grades import EvidenceGrade, ReadDepth
from late_ming_lab.evidence.ledger import (
    CalibrationRole,
    EvidenceLedger,
    PatternRegistry,
    RuleClaimSet,
)
from late_ming_lab.evidence.registry import (
    EVIDENCE_CLUSTERS,
    AccessCondition,
    SourceRegistry,
    Verification,
)
from late_ming_lab.evidence.snapshots import SnapshotManifest

GRADES_IN_ORDER: Final[tuple[EvidenceGrade, ...]] = (
    EvidenceGrade.A,
    EvidenceGrade.B,
    EvidenceGrade.C,
    EvidenceGrade.D,
    EvidenceGrade.S,
)

SUPPORT_IN_ORDER: Final[tuple[SupportClass, ...]] = (
    SupportClass.EVIDENCE_BACKED,
    SupportClass.THEORETICALLY_ASSUMED,
    SupportClass.EXPLORATORY,
)


def _grade_counts(grades: list[EvidenceGrade]) -> str:
    counts = Counter(grade.value for grade in grades)
    return ", ".join(f"{grade.value}:{counts.get(grade.value, 0)}" for grade in GRADES_IN_ORDER)


def coverage_report(
    *,
    registry: SourceRegistry,
    ledger: EvidenceLedger,
    cards: ParameterCards,
    patterns: PatternRegistry,
    rules: RuleClaimSet,
    snapshots: SnapshotManifest,
) -> str:
    """Per-cluster and per-rule coverage, with the breaks named rather than summarised away."""
    rendered_support = ", ".join(
        f"{name}:{count}" for name, count in sorted(support_summary(rules).items())
    )
    rendered_roles = ", ".join(
        f"{role.value}:{len(patterns.by_role(role))}" for role in CalibrationRole
    )
    lines: list[str] = [
        "# Evidence coverage",
        "",
        "Generated by `late_ming_lab.evidence.coverage` from the source registry, the evidence",
        "ledger, the parameter cards, the rule claims and the pattern registry. Every count in it",
        "is counted, not estimated.",
        "",
        f"- sources: {len(registry)} ({_grade_counts([r.grade for r in registry])})",
        f"- ledger entries: {len(ledger)}",
        f"- parameter cards: {len(cards)} "
        f"({_grade_counts([card.evidence_grade for card in cards])})",
        f"- declared rules: {len(rules)} ({rendered_support})",
        f"- historical patterns: {len(patterns)} ({rendered_roles})",
        f"- verification: {_verification_counts(registry)}",
        f"- read depth: {_read_depth_counts(registry)}",
        f"- snapshots recorded: {len(snapshots)} "
        f"({len(snapshots.acquired_records)} acquired, {len(snapshots.pending_records)} "
        f"pending); licences: {_licence_counts(snapshots)}",
        "",
        "## By cluster",
        "",
        "| cluster | sources | layers | claims (strength) | parameters supported | patterns |",
        "| --- | --- | --- | --- | --- | --- |",
    ]
    for cluster in EVIDENCE_CLUSTERS:
        sources = registry.by_cluster(cluster)
        entries = ledger.by_cluster(cluster)
        cluster_patterns = patterns.by_cluster(cluster)
        layers = Counter(source.layer.value for source in sources)
        strengths = Counter(entry.strength.value for entry in entries)
        supported: set[str] = set()
        for entry in entries:
            supported.update(entry.supports_parameters)
        rendered_layers = (
            ", ".join(f"{name}:{count}" for name, count in sorted(layers.items())) or "-"
        )
        rendered_strengths = (
            ", ".join(f"{name}:{count}" for name, count in sorted(strengths.items())) or "-"
        )
        lines.append(
            f"| {cluster} | {len(sources)} | {rendered_layers} | {rendered_strengths} | "
            f"{len(supported)} | {len(cluster_patterns)} |"
        )

    lines += [
        "",
        "## Parameters by support class and grade",
        "",
        "| parameter set | cards | evidence-backed | theoretically-assumed | exploratory | "
        "grades |",
        "| --- | --- | --- | --- | --- | --- |",
    ]
    sets = sorted({card.parameter_set for card in cards})
    for parameter_set in sets:
        group = cards.for_set(parameter_set)
        classes = Counter(card.support_class.value for card in group)
        lines.append(
            f"| {parameter_set} | {len(group)} | "
            f"{classes.get(SupportClass.EVIDENCE_BACKED.value, 0)} | "
            f"{classes.get(SupportClass.THEORETICALLY_ASSUMED.value, 0)} | "
            f"{classes.get(SupportClass.EXPLORATORY.value, 0)} | "
            f"{_grade_counts([card.evidence_grade for card in group])} |"
        )

    lines += [
        "",
        "## Rules",
        "",
        "| rule | support class | parameters | ledger entries |",
        "| --- | --- | --- | --- |",
    ]
    for rule in rules:
        lines.append(
            f"| {rule.name} | {rule.support_class.value} | {len(rule.parameters)} | "
            f"{len(rule.ledger_entries)} |"
        )

    orphan_entries = sorted(
        {
            entry_id
            for rule in rules
            for entry_id in rule.ledger_entries
            if not any(entry.id == entry_id for entry in ledger)
        }
    )
    dangling_parameters = sorted(
        {
            parameter
            for entry in ledger
            for parameter in entry.supports_parameters
            if not _parameter_is_declared(cards, parameter)
        }
    )
    lines += [
        "",
        "## Breaks in the chain",
        "",
        f"- ledger entries cited by a rule but absent from the ledger: "
        f"{', '.join(orphan_entries) if orphan_entries else 'none'}",
        f"- parameters cited by a claim but absent from the cards: "
        f"{', '.join(dangling_parameters) if dangling_parameters else 'none'}",
        f"- clusters with no sources: {', '.join(registry.clusters_without_sources()) or 'none'}",
        f"- clusters with no ledger entries: "
        f"{', '.join(ledger.clusters_without_entries()) or 'none'}",
        f"- clusters with no recorded pattern: "
        f"{', '.join(patterns.clusters_without_patterns()) or 'none'}",
        "",
    ]
    lines += _rights_section(registry, snapshots)
    lines += _read_depth_section(registry, ledger)
    return "\n".join(lines)


def _verification_counts(registry: SourceRegistry) -> str:
    verified = sum(1 for source in registry if source.verification is Verification.VERIFIED)
    unverified = len(registry) - verified
    return f"{verified} verified, {unverified} unverified"


def _read_depth_counts(registry: SourceRegistry) -> str:
    counts = Counter(source.read_depth.value for source in registry)
    return ", ".join(f"{depth.value}:{counts.get(depth.value, 0)}" for depth in ReadDepth)


def _licence_counts(snapshots: SnapshotManifest) -> str:
    counts = Counter(record.rights.status.value for record in snapshots)
    return ", ".join(f"{name}:{count}" for name, count in sorted(counts.items()))


def _rights_section(registry: SourceRegistry, snapshots: SnapshotManifest) -> list[str]:
    """Access, licence and redistribution, per source and per snapshot."""
    access = Counter(source.access.value for source in registry)
    lines: list[str] = [
        "## Access, licence and redistribution",
        "",
        "How each source can be reached, and what the project may do with the bytes it holds. A",
        "raw snapshot is never a tracked file: every one lives under `data/raw/private/`, which",
        "git ignores, and `derived_output_rule` in the snapshot record says what may be published",
        "instead.",
        "",
        "| access condition | sources |",
        "| --- | --- |",
    ]
    for condition in AccessCondition:
        lines.append(f"| {condition.value} | {access.get(condition.value, 0)} |")
    lines += [
        "",
        f"- human-only or institution-gated: {', '.join(registry.human_only_ids) or 'none'}",
        f"- snapshots whose bytes may be redistributed: "
        f"{', '.join(r.id for r in snapshots if r.raw_publishable) or 'none'}",
        f"- snapshots held locally only (record and rule in git, file not): "
        f"{', '.join(r.id for r in snapshots.local_only_records) or 'none'}",
        "",
        "| snapshot | source | version | licence | redistribution | acquired | sha256 |",
        "| --- | --- | --- | --- | --- | --- | --- |",
    ]
    for record in snapshots:
        digest = (record.acquisition.sha256 or "-")[:12]
        acquired = "yes" if record.acquired else record.acquisition.method.value
        lines.append(
            f"| {record.id} | {record.source_id} | {record.version} | "
            f"{record.rights.status.value} | {record.rights.redistribution.value} | "
            f"{acquired} | {digest} |"
        )
    lines.append("")
    return lines


def _read_depth_section(registry: SourceRegistry, ledger: EvidenceLedger) -> list[str]:
    """What was read, and which claims are graded above what was read."""
    crossed = Counter((source.read_depth.value, source.verification.value) for source in registry)
    lines: list[str] = [
        "## What was read",
        "",
        "A verified record means the bibliographic identity was confirmed against a page that was",
        "loaded. It does not mean the source was read. This is the difference, and the claims that",
        "sit on the wrong side of it.",
        "",
        "| read depth | verified | unverified |",
        "| --- | --- | --- |",
    ]
    for depth in ReadDepth:
        verified = crossed.get((depth.value, Verification.VERIFIED.value), 0)
        unverified = crossed.get((depth.value, Verification.UNVERIFIED.value), 0)
        lines.append(f"| {depth.value} | {verified} | {unverified} |")
    by_id = {source.id: source for source in registry}
    over_claimed = [
        entry
        for entry in ledger
        if entry.evidence_grade in {EvidenceGrade.A, EvidenceGrade.B}
        and entry.sources
        and all(
            by_id[source_id].read_depth is ReadDepth.IDENTITY_ONLY
            for source_id in entry.sources
            if source_id in by_id
        )
        and all(source_id in by_id for source_id in entry.sources)
    ]
    lines += [
        "",
        f"{len(over_claimed)} of {len(ledger)} ledger entries carry grade A or B while every",
        "source behind them is identity-only: the claim is real as a bibliographic fact and",
        "unverified as a statement about the text. They are listed rather than downgraded here,",
        "because a grade is a judgement about a source and belongs to the record:",
        "",
    ]
    if over_claimed:
        for entry in sorted(over_claimed, key=lambda item: item.id):
            sources = ", ".join(f"`{source_id}`" for source_id in entry.sources)
            lines.append(f"- **{entry.id}** ({entry.evidence_grade.value}): {sources}")
    else:
        lines.append("- none")
    lines.append("")
    return lines


def _parameter_is_declared(cards: ParameterCards, qualified: str) -> bool:
    """True when ``Set.field`` names a card in the registry."""
    if "." not in qualified:
        return False
    parameter_set, parameter = qualified.split(".", 1)
    return cards.get(parameter_set, parameter) is not None


def uncertainty_report(cards: ParameterCards, registry: SourceRegistry) -> str:
    """Every parameter's grade, range and reasoning, with the sources behind it and how far
    those sources were read."""
    lines: list[str] = [
        "# Parameter uncertainty",
        "",
        "One row per parameter card. `central` is the value the model currently uses; `range` is",
        "what the evidence would allow instead, and is empty where nobody has established one.",
        "Grade `S` means the value is a model assumption and nothing more. Grade `D` means the",
        "evidence is weak but exists. Both are sensitivity candidates by the project's rule.",
        "",
        f"- cards: {len(cards)}",
        f"- with a stated range: {sum(1 for c in cards if c.range and c.range.has_bounds)}",
        f"- grade S: {sum(1 for c in cards if c.evidence_grade is EvidenceGrade.S)}",
        f"- grade D: {sum(1 for c in cards if c.evidence_grade is EvidenceGrade.D)}",
        f"- sensitivity candidates: {len(cards.sensitivity_candidates)}",
        f"- cards whose sources are all identity-only: {_identity_only_cards(cards, registry)}",
        "",
        "## Cards",
        "",
        "| parameter | set | grade | class | central | unit | range | range basis | sensitivity |",
        "| --- | --- | --- | --- | --- | --- | --- | --- | --- |",
    ]
    for card in cards:
        if card.range and card.range.has_bounds:
            spread = f"{card.range.low}-{card.range.high}"
            basis = card.range.basis.replace("|", "/")
        else:
            spread = "—"
            basis = "—"
        central = card.value_in_use.replace("|", "/") or "-"
        lines.append(
            f"| {card.id} | {card.parameter_set} | {card.evidence_grade.value} | "
            f"{card.support_class.value} | {central} | {card.unit} | {spread} | {basis} | "
            f"{card.sensitivity_priority} |"
        )

    lines += [
        "",
        "## Sources behind each card, and how far they were read",
        "",
        "`identity` means the bibliographic record was confirmed and the text was not read;",
        "`abstract` means an abstract was read; `full-text` means the passage was read. A sourced",
        "card whose sources are all identity-only is a value resting on a title.",
        "",
        "| card | grade | sources | verification and read depth |",
        "| --- | --- | --- | --- |",
    ]
    for card in cards:
        if not card.sources:
            lines.append(f"| {card.id} | {card.evidence_grade.value} | — | — |")
            continue
        marks = []
        for source_id in card.sources:
            source = registry.require(source_id)
            marks.append(f"`{source_id}` {source.verification.value}/{source.read_depth.value}")
        lines.append(
            f"| {card.id} | {card.evidence_grade.value} | {len(card.sources)} | "
            f"{'; '.join(marks)} |"
        )
    lines.append("")

    conflicts = [card for card in cards if card.range is not None and card.range.conflicts]
    lines += ["", "## Recorded conflicts", ""]
    if conflicts:
        for card in conflicts:
            recorded = card.range
            assert recorded is not None
            lines.append(f"- **{card.parameter_set}.{card.id}**: {recorded.conflicts}")
    else:
        lines.append("- none: no card currently records two sources that disagree.")
    lines.append("")
    return "\n".join(lines)


def _identity_only_cards(cards: ParameterCards, registry: SourceRegistry) -> int:
    """Cards that cite sources and every one of them is identity-only."""
    return sum(
        1
        for card in cards
        if card.sources
        and all(
            registry.require(source_id).read_depth is ReadDepth.IDENTITY_ONLY
            for source_id in card.sources
            if registry.has(source_id)
        )
        and all(registry.has(source_id) for source_id in card.sources)
    )


def gap_report(
    *,
    registry: SourceRegistry,
    ledger: EvidenceLedger,
    cards: ParameterCards,
    patterns: PatternRegistry,
    rules: RuleClaimSet,
    snapshots: SnapshotManifest,
) -> str:
    """What is missing, including the acquisition queue that only a human may work."""
    unverified = [source for source in registry if source.verification is Verification.UNVERIFIED]
    restricted = [source for source in registry if source.acquisition_is_human_only]
    unexplained_rules = [
        rule
        for rule in rules
        if not rule.ledger_entries and rule.support_class is not SupportClass.EXPLORATORY
    ]
    bare_parameters = [
        card for card in cards if card.evidence_grade is EvidenceGrade.S and not card.sources
    ]
    unreferenced_parameters = [card for card in bare_parameters if not card.ledger_entries]
    lines: list[str] = [
        "# Evidence gaps",
        "",
        "Generated from the registries. A gap is a place where the chain from claim to code is",
        "missing, not a place where the model is wrong.",
        "",
        "## Clusters",
        "",
    ]
    for cluster in EVIDENCE_CLUSTERS:
        missing: list[str] = []
        if not registry.by_cluster(cluster):
            missing.append("no sources")
        if not ledger.by_cluster(cluster):
            missing.append("no claims")
        if not patterns.by_cluster(cluster):
            missing.append("no pattern")
        lines.append(f"- **{cluster}**: {'; '.join(missing) if missing else 'covered'}")

    lines += [
        "",
        "## Rules with no evidence behind them",
        "",
        f"{len(unexplained_rules)} declared rule(s) cite no ledger entry and are not declared",
        "exploratory. Each is either a rule waiting for evidence or a rule mislabelled as",
        "theoretically assumed:",
        "",
    ]
    for rule in unexplained_rules:
        lines.append(f"- **{rule.name}** (`{rule.module}`, class `{rule.support_class.value}`)")
    if not unexplained_rules:
        lines.append("- none")

    framed = [card for card in bare_parameters if card.ledger_entries]
    lines += [
        "",
        "## Parameters whose value is still ours",
        "",
        f"{len(bare_parameters)} of {len(cards)} parameters are grade S with no source fixing the",
        f"value. Of those, {len(framed)} are framed by at least one ledger claim (the record",
        f"establishes the mechanism and its order of magnitude) and {len(unreferenced_parameters)}",
        "have no claim attached at all — those are the thinnest places in the model:",
        "",
    ]
    by_set = Counter(card.parameter_set for card in bare_parameters)
    unreferenced_by_set = Counter(card.parameter_set for card in unreferenced_parameters)
    for name, count in sorted(by_set.items()):
        total = len(cards.for_set(name))
        lines.append(
            f"- {name}: {count} of {total} grade S "
            f"({unreferenced_by_set.get(name, 0)} with no claim attached)"
        )

    lines += [
        "",
        "## Unverified bibliographic records",
        "",
        f"{len(unverified)} of {len(registry)} source records were recorded but not confirmed",
        "against a locator in this phase. A claim resting on one may not exceed grade C:",
        "",
    ]
    for source in unverified:
        lines.append(f"- `{source.id}` — {source.title} ({source.layer.value})")
        lines.append(f"  - next action: {source.next_action}")
    if not unverified:
        lines.append("- none")

    lines += [
        "",
        "## Acquisition queue (human only)",
        "",
        "These sources are behind institutional or manual access. **No agent may acquire them**;",
        "the registry records the condition and the locator, and a human decides what to consult:",
        "",
    ]
    for source in restricted:
        note = source.rights_note or "access condition not described"
        lines.append(f"- `{source.id}` — {source.access.value}: {note}")
    if not restricted:
        lines.append("- none")

    lines += [
        "",
        "## Inputs acquired, and inputs still owed",
        "",
        f"{len(snapshots)} snapshot(s) are recorded in `sources/snapshots/`: "
        f"{len(snapshots.acquired_records)} acquired and hashed,",
        f"{len(snapshots.pending_records)} pending. A raw file is never tracked; what the",
        "repository keeps is the record, the derived-output rule and the hash.",
        "",
        "| snapshot | source | licence | redistribution | state | next step |",
        "| --- | --- | --- | --- | --- | --- |",
    ]
    for record in snapshots:
        state = "acquired" if record.acquired else record.acquisition.method.value
        if record.acquired:
            next_step = record.derived_output_rule.split(". ")[0].rstrip(".") + "."
        else:
            next_step = record.acquisition.human_note
        lines.append(
            f"| {record.id} | {record.source_id} | {record.rights.status.value} | "
            f"{record.rights.redistribution.value} | {state} | {next_step} |"
        )
    unresolved = [record for record in snapshots if record.rights.unresolved_question]
    lines += [
        "",
        "## Licence questions that are still open",
        "",
        "An unresolved licence is recorded as a question, not as permission. Until an answer is on",
        "file, the rule is: aggregated derived output may be published with attribution, the file",
        "and any transcription of it may not.",
        "",
    ]
    if unresolved:
        for record in unresolved:
            lines.append(
                f"- **{record.id}** ({record.rights.status.value}): "
                f"{record.rights.unresolved_question}"
            )
    else:
        lines.append("- none")
    lines += [
        "",
        "## Structural gaps this phase did not close",
        "",
        "- No source in the registry measures a 1625-1644 Shaanxi-Henan quantity directly at the",
        "  resolution the model uses (county-month). Where a claim carries a magnitude, it is a",
        "  regional or annual figure being used at a finer resolution, and the card says so.",
        "- The registry holds no archival material: county-level quota books, relief registers and",
        "  garrison payrolls are named as gaps rather than approximated.",
        "- Nothing here calibrates anything. Every pattern carries a calibration role, and the",
        "  hold-out patterns are marked so a later phase cannot silently fit them.",
        "",
    ]
    return "\n".join(lines)


def grade_summary(cards: ParameterCards) -> dict[str, int]:
    """Grade counts over the cards, for the phase report and for tests."""
    counts = Counter(card.evidence_grade.value for card in cards)
    return {grade.value: counts.get(grade.value, 0) for grade in GRADES_IN_ORDER}


def support_summary(rules: RuleClaimSet) -> dict[str, int]:
    """Rule counts by support class, for the phase report and for tests."""
    counts = Counter(rule.support_class.value for rule in rules)
    return {support.value: counts.get(support.value, 0) for support in SUPPORT_IN_ORDER}
