"""Deriving the tick order's dependency structure from the registered systems.

:mod:`late_ming_lab.core.tick` fixes *when* each phase runs; this module derives *why* that
order matters. Every system declares the resources of the tick vocabulary it reads and writes,
and :func:`validate` refuses a registration in which a system would read a resource earlier in
the tick than the earliest system that writes it.

The claim is phase-level, not a field-level dataflow analysis: a system names the shared
resources whose ordering it depends on, not every attribute it touches. A resource nothing
writes is allowed to be read — that is initial actor state, established before the first tick.

The diagram in ``docs/architecture/system-dependency.md`` is generated from the registrations by
:func:`as_mermaid`, so the picture cannot drift from the code it describes.
"""

from __future__ import annotations

from collections.abc import Iterable
from dataclasses import dataclass

from late_ming_lab.core.hashing import canonical_json, hash_text
from late_ming_lab.core.tick import TICK_ORDER_VERSION, System, TickPhase


class SchedulerError(ValueError):
    """Raised when systems violate the versioned tick order or their dependency claims."""


@dataclass(frozen=True, slots=True)
class SystemRegistration:
    """One system's tick phase and its phase-level dependency claim."""

    name: str
    phase: TickPhase
    reads: frozenset[str]
    writes: frozenset[str]


@dataclass(frozen=True, slots=True)
class DependencyEdge:
    """One writer-reader pair for one shared resource, and whether the tick order honours it."""

    resource: str
    writer: str
    writer_phase: TickPhase
    reader: str
    reader_phase: TickPhase
    satisfied: bool


def registrations(systems: Iterable[System]) -> tuple[SystemRegistration, ...]:
    """The systems' names, phases and dependency claims, in registration order."""
    return tuple(
        SystemRegistration(
            name=system.name,
            phase=system.phase,
            reads=frozenset(system.reads),
            writes=frozenset(system.writes),
        )
        for system in systems
    )


def validate(systems: Iterable[System]) -> tuple[System, ...]:
    """Validate the registration contract and return the systems unchanged.

    Three rules: names must be non-empty and unique, systems must follow the versioned tick
    order, and no system may read a resource in an earlier phase than the earliest writer of
    that resource. The first two are the kernel's original registration checks; the third is
    the phase-level dependency claim the systems declare.
    """
    validated = tuple(systems)
    seen: set[str] = set()
    previous: TickPhase | None = None
    for system in validated:
        if not system.name:
            raise SchedulerError("system name must not be empty")
        if system.name in seen:
            raise SchedulerError(f"duplicate system name {system.name!r}")
        seen.add(system.name)
        if previous is not None and system.phase < previous:
            raise SchedulerError(
                f"system {system.name!r} registers in phase {system.phase.token!r} after "
                f"{previous.token!r}; systems must follow the versioned tick order"
            )
        previous = system.phase

    regs = registrations(validated)
    earliest = _earliest_writers(regs)
    for edge in _dependency_edges(regs):
        if edge.satisfied:
            continue
        source = earliest[edge.resource]
        raise SchedulerError(
            f"system {edge.reader!r} reads {edge.resource!r} in phase {edge.reader_phase.token!r}, "
            f"before its earliest writer {source.name!r} in phase {source.phase.token!r}; a system "
            "must not consume state a later phase produces"
        )
    return validated


def dependency_report(systems: Iterable[System]) -> tuple[DependencyEdge, ...]:
    """One edge per (resource, writer, reader) pair, sorted, with the rule's verdict."""
    return _dependency_edges(registrations(systems))


def as_mermaid(systems: Iterable[System]) -> str:
    """Render the registered systems and their shared resources as a Mermaid ``flowchart``.

    A system is a node labelled ``phase-token: name``; an edge runs from a writer to a reader for
    every resource they share, and parallel edges between the same pair collapse into one
    comma-joined label. Node and edge order are sorted, so the output is deterministic.
    """
    regs = registrations(systems)
    lines = [
        f"%% {TICK_ORDER_VERSION} — generated by core.scheduler.as_mermaid",
        "flowchart LR",
    ]
    for reg in sorted(regs, key=lambda reg: (reg.phase, reg.name)):
        lines.append(f'    {_node_id(reg.name)}["{reg.phase.token}: {reg.name}"]')
    for writer, reader, resources in _shared_resources(regs):
        lines.append(f"    {_node_id(writer)} -->|{', '.join(resources)}| {_node_id(reader)}")
    return "\n".join(lines)


def systems_digest(systems: Iterable[System]) -> str:
    """SHA-256 over the canonical form of the registrations.

    The payload is ``(name, phase value, sorted reads, sorted writes)`` per system in
    registration order, so the digest moves whenever a system is added, reordered, rephased or
    has a dependency claim changed — and only then.
    """
    payload = [
        [reg.name, int(reg.phase), sorted(reg.reads), sorted(reg.writes)]
        for reg in registrations(systems)
    ]
    return hash_text(canonical_json(payload))


def describe_table(systems: Iterable[System]) -> str:
    """A plain-text ``phase | system | reads | writes`` table of the registrations."""
    rows = [
        (
            reg.phase.token,
            reg.name,
            _resource_cell(reg.reads),
            _resource_cell(reg.writes),
        )
        for reg in registrations(systems)
    ]
    header = ("phase", "system", "reads", "writes")
    widths = [max(len(row[column]) for row in (header, *rows)) for column in range(len(header))]
    lines = [_table_row(header, widths), _table_row(("-" * width for width in widths), widths)]
    lines.extend(_table_row(row, widths) for row in rows)
    return "\n".join(lines)


def _dependency_edges(regs: tuple[SystemRegistration, ...]) -> tuple[DependencyEdge, ...]:
    earliest = _earliest_writers(regs)
    edges = [
        DependencyEdge(
            resource=resource,
            writer=writer.name,
            writer_phase=writer.phase,
            reader=reader.name,
            reader_phase=reader.phase,
            satisfied=reader.phase >= earliest[resource].phase,
        )
        for writer in regs
        for resource in writer.writes
        for reader in regs
        if resource in reader.reads
    ]
    return tuple(
        sorted(
            edges,
            key=lambda edge: (
                edge.resource,
                edge.writer_phase,
                edge.writer,
                edge.reader_phase,
                edge.reader,
            ),
        )
    )


def _earliest_writers(regs: tuple[SystemRegistration, ...]) -> dict[str, SystemRegistration]:
    earliest: dict[str, SystemRegistration] = {}
    for reg in regs:
        for resource in reg.writes:
            current = earliest.get(resource)
            if current is None or reg.phase < current.phase:
                earliest[resource] = reg
    return earliest


def _shared_resources(
    regs: tuple[SystemRegistration, ...],
) -> tuple[tuple[str, str, tuple[str, ...]], ...]:
    """Writer name, reader name and the sorted resources that produce the edge."""
    phases = {reg.name: reg.phase for reg in regs}
    edges: list[tuple[str, str, tuple[str, ...]]] = []
    for writer in regs:
        for reader in regs:
            shared = tuple(sorted(writer.writes & reader.reads))
            if shared:
                edges.append((writer.name, reader.name, shared))
    edges.sort(key=lambda edge: (phases[edge[0]], edge[0], phases[edge[1]], edge[1]))
    return tuple(edges)


def _node_id(name: str) -> str:
    """A Mermaid-safe node id: the registered name with its separators flattened."""
    return name.replace("-", "_")


def _resource_cell(resources: frozenset[str]) -> str:
    return ", ".join(sorted(resources)) if resources else "-"


def _table_row(cells: Iterable[str], widths: list[int]) -> str:
    return " | ".join(cell.ljust(width) for cell, width in zip(cells, widths, strict=True))
